version: "3.8"
services:
  security:
    build: ./security
    image: ibrahimaddandan/security:latest
    ports:
        - "3000:3000"
    deploy:
        replicas: 2
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 60s
